### ISSUE TITLE
[ pack ] Test failures during generation of nightly require user interaction

### ISSUE THREAD

**Issue by stefan-hoeck** [buzden/idris2-golden-runner-helper#3]
After merging elab-util, I'm getting some test failures for this library. These require user interaction, so they are probably going to hold generation of the next nightly.

**Comment by buzden** [comment]
Are these failures stable? I thought that the last change (independently of changes in `elab-util`) could lead to some failures in the following scenario: imagine that I have several tests which are run in parallel by this runner-helper, **and** each test does `pack install-dependencies` in their `run` script. Can this lead to some problems with compilation, when `pack` is asked to install the same libraries simultaneously?

**Comment by buzden** [comment]
Oh, it seems that I misunderstood you. Do you mean that during the check in CI failed test asked interactively for whether update the golden value?

**Comment by stefan-hoeck** [comment]
> Are these failures stable? I thought that the last change (independently of changes in `elab-util`) could lead to some failures in the following scenario: imagine that I have several tests which are run in parallel by this runner-helper, **and** each test does `pack install-dependencies` in their `run` script. Can this lead to some problems with compilation, when `pack` is asked to install the same libraries simultaneously?

I don't about how stable they are. I just ran a general collection test this morning on my machine to figure out if there still are libraries, which fail to build with the new elab-util. And there I got test failures. Whether that's because pack is being run from a running pack instance, I don't know.

**Comment by stefan-hoeck** [comment]
> Oh, it seems that I misunderstood you. Do you mean that during the check in CI failed test asked interactively for whether update the golden value?

Yes. I'm being asked whether I want to keep the new expected output.

**Comment by stefan-hoeck** [comment]
> > Oh, it seems that I misunderstood you. Do you mean that during the check in CI failed test asked interactively for whether update the golden value?
> 
> Yes. I'm being asked whether I want to keep the new expected output.

Well, again, I'm not sure if this happens during CI, but it happened during my local collection check, which does the same thing, CI will be doing.

**Comment by buzden** [comment]
> > > Oh, it seems that I misunderstood you. Do you mean that during the check in CI failed test asked interactively for whether update the golden value?
> > 
> > 
> > Yes. I'm being asked whether I want to keep the new expected output.
> 
> Well, again, I'm not sure if this happens during CI, but it happened during my local collection check, which does the same thing, CI will be doing.

When tests are run in CI, the `CI` environment variable is set, which is used as a sign for the `golden-runner-helper` to use non-interactive mode. The `CI` variable is more or less common agreement between different CI systems.

**Comment by stefan-hoeck** [comment]
Thanks for the info about the CI variable. I didn't know that.

**Comment by stefan-hoeck** [comment]
I'll leave this open and see, how tonight's nightly works out. If all goes well, I'll close this and the issue on summary-stat.

**Comment by stefan-hoeck** [comment]
So, two notes on this: Concerning the pack-db, this has been resolved. The `CI` variable turns interactive mode off, as you said. I still get test failures on my machine, and I think they have to do with colored output in hedgehog. I have `HEDGEHOG_COLOR=1` set as a default on my machine. If I remove this, the tests pass, otherwise they fail.

I'm going to close this, as the main issue described in the title has been resolved.
